In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [5]:
x_train.shape

torch.Size([3, 1])

In [6]:
y_train.shape

torch.Size([3, 1])

In [4]:
W = torch.zeros(1, requires_grad=True)
W

tensor([0.], requires_grad=True)

In [5]:
b = torch.zeros(1, requires_grad=True)
b

tensor([0.], requires_grad=True)

In [9]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [10]:
# MSE
cost = torch.mean((hypothesis - y_train)**2)
cost

tensor(18.6667, grad_fn=<MeanBackward0>)

In [6]:
optimizer = optim.SGD([W, b], lr=0.01)

In [ ]:
# gradient를 0으로 초기화
optimizer.zero_grad() 
# 비용 함수를 미분하여 gradient 계산
cost.backward() 
# W와 b를 업데이트
optimizer.step() 

In [8]:
epochs = 2000
for epoch in range(epochs+1):
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 1.997, b: 0.006 Cost: 0.000005
Epoch  100/2000 W: 1.998, b: 0.005 Cost: 0.000003
Epoch  200/2000 W: 1.998, b: 0.004 Cost: 0.000002
Epoch  300/2000 W: 1.999, b: 0.003 Cost: 0.000001
Epoch  400/2000 W: 1.999, b: 0.002 Cost: 0.000001
Epoch  500/2000 W: 1.999, b: 0.002 Cost: 0.000000
Epoch  600/2000 W: 1.999, b: 0.001 Cost: 0.000000
Epoch  700/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  800/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  900/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1000/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1100/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1200/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1300/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1400/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1500/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1600/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1700/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1800/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1900/2000 W: 2.000, b: 0.000 Cost: 0.000000
