In [5]:
import torch
import numpy as np

In [8]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


### 3차원 텐서에서 2차원 텐서로 변경

In [9]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


### 3차원 텐서의 크기 변경

In [10]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 스퀴즈 (1인 차원 제거)

In [12]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [13]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### 언스퀴즈 (1인 차원 추가)

In [20]:
ft = torch.Tensor([0, 1, 2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [15]:
# 첫 번째 차원에 1인 차원 추가
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [18]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [19]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [21]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [22]:
ft.long()

tensor([0, 1, 2])

In [23]:
ft.float()

tensor([0., 1., 2.])

### 연결하기

In [24]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [25]:
# 첫 번째 차원 늘어남
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [26]:
# 두 번째 차원 늘어남
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### 스택킹

In [27]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [28]:
torch.stack([x, y, z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [29]:
torch.stack([x, y, z], dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 0, 1

In [31]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [32]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [33]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 덮어쓰기 연산

In [35]:
x = torch.FloatTensor([[1, 2], [3, 4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [36]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
