In [1]:
import torch

In [2]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [4]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [5]:
t2 = torch.FloatTensor([[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.],
                        [10., 11., 12.]])
t2

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [6]:
print(t2.dim())
print(t2.shape)

2
torch.Size([4, 3])


In [8]:
t2[:, 1]

tensor([ 2.,  5.,  8., 11.])

In [9]:
t2[:, :-1]

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

In [10]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [11]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [12]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


#### 행렬곱

In [13]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


#### 원소곱

In [14]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [15]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [16]:
t2.mean()

tensor(6.5000)

In [17]:
t2.mean(dim=0)

tensor([5.5000, 6.5000, 7.5000])

In [18]:
t2.sum(dim=0)

tensor([22., 26., 30.])

In [19]:
t2.max()

tensor(12.)

In [20]:
t2.max(dim=0)

torch.return_types.max(
values=tensor([10., 11., 12.]),
indices=tensor([3, 3, 3]))